services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/simple-blc
    environment:
      FLASK_ENV: development
    links:
      - db
  db:
    image: mongo:4.4.5-bionic
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=test_mongodb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017

